# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f2596027db0161240796060cc1f3694ea15635f9d3a90d64737c24aea8a0199dc5373803567dbef00201eafba68ff2701068ebdf3bdbcf7bdc2b795e0d32bd77

test:
  secret_key_base: efb9a32221e51e7c3766e47bd276d9413b442a7e7bc16cb5b4cb53f258a04a6cd637c861869103dbbe81c506bf84f491c128a0081184378b3be51c747b2e0cd0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
